version: '3'

services:
  nginx-service:
    container_name: nginx-container
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ../:/var/www/symf_project/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
    ports:
      - "8080:80"
    depends_on:
      - php74-service

  php74-service:
    build:
      context: ./php
    restart: always
    volumes:
      - ../:/var/www/symf_project
    expose:
      - "9000"
    depends_on:
      - rabbitmq
      - mysql-service
  
  supervisor:
    build:
      context: ./supervisor
    restart: always
    volumes:
      - ../:/var/www/symf_project
    depends_on:
      - rabbitmq
      - mysql-service

  cronjob-service:
    build:
      context: ./cronjob
    restart: always
    volumes:
      - ../:/var/www/symf_project
    depends_on:
      - rabbitmq
      - mysql-service
  
  mysql-service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
        - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports: 
        - "15672:15672"
        - "5672:5672"